apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qg2a
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bfks-tenant/rhtap-demo-app/hacbs-test-project-qg2a@sha256:d42e10bd361fc95e39be54509501f4f9be3273f6e880887af2e614390993214c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
