apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qg2a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qg2a
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qg2a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qg2a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qg2a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bfks-tenant/rhtap-demo-app/hacbs-test-project-qg2a@sha256:4f8da1292f3a862b26cdb8403e6e66b43bb7954f4d38eb269998edf4b6a31af5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
